name: Dig
main: com.github.himaaaatti.spigot.plugin.dig.Dig
version: 0.1

commands:
   dig:
     description: This is a dig command.
     usage: /<command>
     permission:
     permission-message: You don't have <permission>